# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19G1fc0eak7sangreA-l9raZEusangre19hz6OsangresangreOOL
"""

paciente = input("La persona esta en ayunas o posprandial ")
# Ingresar solamente la palabra "ayunas" o "posprandial" en minusculas.
sangre = float(input("El nivel de glucosa en sangre (mg/dl) es "))

if paciente =='ayunas':
  if sangre<70:
    print("hipoglucemia")
  elif 70 <= sangre < 100:
    print("no diabetes")
  elif 100 <= sangre < 125:
    print("pre diabetes")
  else:
    print("diabetes")  
elif paciente =='posprandrial':
  if sangre<140:
    print("no diabetes")
  elif 140 <= sangre < 200:
    print("pre diabetes")
  else:
    print("diabetes")
else:
  print("Error en los datos")

paciente = input("La persona está en ayunos (Y/N) ")
sangre = int(input("Ingresar glucosa en sangre (mg/dl)"))

if (paciente == 'ayuno' and sangre<70):
  print("Hipoglucemia")
elif (paciente == 'ayuno' and 70<=sangre<=100) or (paciente =='posprandial' and sangre<140):
  print("No diabetes")
elif (paciente == 'ayuno' and 100<=sangre<=125) or (paciente =='posprandial' and 140<=sangre<=200):
  print("prediabetes")
elif (paciente == 'ayuno' and 100<=sangre<=125) or (paciente =='posprandial' and 140<=sangre<=200):
  print("diabetes")
else:
  print("Error en los datos")

peso   = float(input("Ingresar peso en kilogramos (Kg)"))
altura = float(input("Ingresar altura en metros (m)"))

imc = peso/(altura**2)

if imc < 18.5:
  print("Bajo de peso")
elif 18.5 <= imc < 25:
  print("Peso normal")
elif 25 <= imc < 30:
  print("Sobrepeso")
else:
  print("Obeso")